services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CreateContentBlockHandler:
    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\UpdateContentBlockHandler:
    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\DeleteContentBlockHandler:

    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocaleHandler:
