build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - app/*
        - bin/*
        - docs/*
        - src/Backend/Core/Js/ckfinder/*
        - src/Backend/Core/Js/ckeditor/*
        - var/*
        - vendor/*

tools:
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_cpd: false
    php_sim: true
    php_pdepend:
        excluded_dirs:
            - vendor

application:
    symfony2:
        autoload_file: autoload.php
    dependencies:
        before:
            - 'composer install --prefer-dist'

checks:
    php:
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        variable_existence: true
        unused_methods: true
        symfony_request_injection: true
        sql_injection_vulnerabilities: true
        simplify_boolean_return: true
        excluded_dependencies:
            - simple-bus/doctrine-orm-bridge
            - symfony/security-acl
