imports:
    - { resource: config_dev.yml }

parameters:
    site.multilanguage: true
    site.default_language: en

framework:
    test: true
    session:
        storage_factory_id: session.storage.factory.mock_file
    profiler:
        collect: false
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        connections:
            default:
                dbname: "%database.name%_test"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    database:
        class: SpoonDatabase
        arguments:
            - "%database.driver%"
            - "%database.host%"
            - "%database.user%"
            - "%database.password%"
            - "%database.name%_test"
            - "%database.port%"
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8mb4' } ] ]
            # The following line removes the ONLY_FULL_GROUP_BY from the sessions sql_mode, it was added in 5.7
            # and caused some queries to break.
            - [ execute, [ 'SET sql_mode = REPLACE(@@SESSION.sql_mode, "ONLY_FULL_GROUP_BY", "")'] ]
            - [ setDebug, [ "%kernel.debug%" ]]

monolog:
    handlers:
        main:
            type: 'null'
