imports:
    - { resource: console.yml }
    - { resource: parameters_install.yml }
    - { resource: doctrine.yml }

framework:
    secret: "%kernel.secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing_install.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    templating:
        engines: ['twig']
    session:
        handler_id: ~
    validation:
        enable_annotations: true

# Assetic Configuration
assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles: [ 'ForkCMSInstallerBundle' ]
    filters:
        cssrewrite: ~

monolog:
    handlers:
        main:
            type: stream
            path: "%site.path_www%/var/logs/logs.log"
            level: debug

parameters:
    doctrine.dbal.connection_factory.class: ForkCMS\Bundle\InstallerBundle\Service\InstallerConnectionFactory
    fork.is_installed: false

services:
    # dummy service during the installation
    mailer_configurator:
        class: stdClass

    # dummy service during the installation
    fork.settings:
        class: stdClass

    # dummy service during the installation
    cache.pool:
        class: stdClass

    database:
        class: SpoonDatabase
        arguments:
            - "%database.driver%"
            - "%database.host%"
            - "%database.user%"
            - "%database.password%"
            - "%database.name%"
            - "%database.port%"
        calls:
            - [ setDebug, [ "%kernel.debug%" ]]
