services:
  forkcms.console.cache.clear:
    class: Console\Core\CacheClearCommand
    tags:
      - { name: console.command }
  forkcms.console.thumbnails.generate:
    class: Console\Thumbnails\GenerateThumbnailsCommand
    arguments:
      - "@ForkCMS\\Utility\\Thumbnails"
    tags:
      - { name: console.command }
  forkcms.console.mailmotor.remove:
    class: Console\Mailmotor\RemoveMailmotorCommand
    arguments:
      - "@database"
      - "@fork.settings"
      - "@kernel"
    tags:
      - { name: console.command }
