_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
backend:
    path: /private/{_locale}/{module}/{action}
    defaults:
        _controller: \ForkCMS\App\ForkController::backendController
        _locale: ~
        module: ~
        action: ~
backend_ajax:
    path: /backend/ajax
    defaults:
        _controller: \ForkCMS\App\ForkController::backendAjaxController
frontend_ajax:
    path: /frontend/ajax
    defaults:
        _controller: \ForkCMS\App\ForkController::frontendAjaxController
frontend:
    path: /{route}
    defaults:
        _controller: \ForkCMS\App\ForkController::frontendController
        route: ~
    requirements:
        route: (.*)
