services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Common\Sitemap\SitemapGenerator:
        arguments:
            $providers: !tagged sitemap.url_provider
            $projectDir: '%kernel.project_dir%'

    Console\Sitemap\GenerateSitemapCommand:
        tags:
            - { name: console.command }

    Common\Sitemap\PagesSitemapUrlProvider:
        arguments:
            $database: '@database'
        tags:
            - { name: sitemap.url_provider }

    Common\Sitemap\FaqSitemapUrlProvider:
        arguments:
            $database: '@database'
        tags:
            - { name: sitemap.url_provider }

    Common\Sitemap\BlogSitemapUrlProvider:
        arguments:
            $database: '@database'
        tags:
            - { name: sitemap.url_provider }
