set :branch, "staging"
set :staging_server, "dev02.sumocoders.eu"
set :staging_url, "#{project}.#{client}.php71.sumocoders.eu"
set :document_root, "/home/#{user}/php71/#{client}/#{project}"
set :url, "#{staging_url}"
