services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    media_library.cache.media_folder:
        class: Backend\Modules\MediaLibrary\Builder\MediaFolder\MediaFolderCache
        public: true
        arguments:
            - "@cache.pool"
            - "@service_container"
