services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # MediaFolder
  Backend\Modules\MediaLibrary\Domain\MediaFolder\Command\CreateMediaFolderHandler:
  Backend\Modules\MediaLibrary\Domain\MediaFolder\Command\DeleteMediaFolderHandler:
  Backend\Modules\MediaLibrary\Domain\MediaFolder\Command\UpdateMediaFolderHandler:

  # MediaGroup
  Backend\Modules\MediaLibrary\Domain\MediaGroup\Command\SaveMediaGroupHandler:

  # MediaItem
  Backend\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromMovieUrlHandler:
  Backend\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromLocalStorageTypeHandler:
  Backend\Modules\MediaLibrary\Domain\MediaItem\Command\DeleteMediaItemHandler:
  Backend\Modules\MediaLibrary\Domain\MediaItem\Command\UpdateMediaItemHandler:
