services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\MediaLibrary\Domain\MediaGroup\MediaGroupType:

    Backend\Modules\MediaLibrary\Domain\MediaGroup\SingleMediaGroupType:
        arguments:
            - "@media_library.repository.group"
            - "@command_bus"
        tags:
            - { name: form.type }
