services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\MediaLibrary\Domain\MediaGroup\MediaGroupType:
    Backend\Modules\MediaLibrary\Domain\MediaGroup\SingleMediaGroupType:
