services:
    # Frontend helpers
    media_library.helper.frontend:
        class: Frontend\Modules\MediaLibrary\Helper\FrontendHelper
        public: true
        arguments:
            - '@Backend\Modules\MediaLibrary\Domain\MediaGroupMediaItem\MediaGroupMediaItemRepository'
