services:
  media_galleries.handler.create_media_gallery:
    class: Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\CreateMediaGalleryHandler
    arguments:
      - "@media_galleries.repository.gallery"
    tags:
      - { name: command_handler, handles: Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\CreateMediaGallery }

  media_galleries.handler.update_media_gallery:
    class: Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\UpdateMediaGalleryHandler
    tags:
      - { name: command_handler, handles: Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\UpdateMediaGallery }

  media_galleries.handler.delete_media_gallery:
    class: Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\DeleteMediaGalleryHandler
    arguments:
      - "@media_galleries.repository.gallery"
      - "@media_library.repository.item"
    tags:
      - { name: command_handler, handles: Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\DeleteMediaGallery }
