services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\CreateMediaGalleryHandler:
  Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\UpdateMediaGalleryHandler:
  Backend\Modules\MediaGalleries\Domain\MediaGallery\Command\DeleteMediaGalleryHandler:
