services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Backend\Modules\Mailmotor\Domain\Settings\Command\SaveSettingsHandler:
    arguments:
      $modulesSettings: "@fork.settings"
  Frontend\Modules\Mailmotor\Domain\Subscription\Command\SubscriptionHandler:
    arguments:
      $subscriber: "@mailmotor.subscriber"
      $modulesSettings: "@fork.settings"
  Frontend\Modules\Mailmotor\Domain\Subscription\Command\UnsubscriptionHandler:
    arguments:
      $subscriber: "@mailmotor.subscriber"
      $modulesSettings: "@fork.settings"
